### ISSUE TITLE
+saveWithBlock: crashes if SQLite Core Data stack set up in background before first unlock

### ISSUE THREAD

**Issue by trdarr** [magicalpanda/MagicalRecord#594]
Our app is launched in the background because it receives significant location change events. If the app is launched before the device is first unlocked (i.e., if the phone is remains locked for approximately five minutes after a reboot), the Core Data stack setup fails.

```
<Warning>: +[MagicalRecord(ErrorHandling) defaultErrorHandler:](0x2ae808) Error: authorization denied
<Warning>: +[MagicalRecord(ErrorHandling) defaultErrorHandler:](0x2ae808) Error: 23
<Warning>: +[MagicalRecord(ErrorHandling) defaultErrorHandler:](0x2ae808) Error Message: The operation couldn’t be completed. (Cocoa error 256.)
<Warning>: +[MagicalRecord(ErrorHandling) defaultErrorHandler:](0x2ae808) Error Domain: NSCocoaErrorDomain
<Warning>: +[MagicalRecord(ErrorHandling) defaultErrorHandler:](0x2ae808) Recovery Suggestion: (null)
<Warning>: +[NSManagedObjectContext(MagicalRecord) MR_contextWithStoreCoordinator:](0x38714014) -> Created Context UNNAMED
<Warning>: +[NSManagedObjectContext(MagicalRecord) MR_setRootSavingContext:](0x38714014) Set Root Saving Context: <NSManagedObjectContext: 0x16eb16d0>
<Warning>: +[NSManagedObjectContext(MagicalRecord) MR_newMainQueueContext](0x38714014) Created Main Queue Context: <NSManagedObjectContext: 0x16eb1430>
<Warning>: +[NSManagedObjectContext(MagicalRecord) MR_setDefaultContext:](0x38714014) Set Default Context: <NSManagedObjectContext: 0x16eb1430>
```

Inspecting the stack with lldb indicates that that the store is null.

```
(lldb) po [MagicalRecord currentStack]
Current Default Core Data Stack: ----
Model:           {
    …
}
Coordinator:     <NSPersistentStoreCoordinator: 0x16d8d3f0>
Store:           (null)
Default Context: <NSManagedObjectContext (0x16eb1430): *** DEFAULT ***> on *** MAIN THREAD ***
Context Chain:

- DEFAULT (0x16eb1430) (*)
- BACKGROUND SAVING (ROOT) (0x16eb16d0)
```

When the app is launched from Springboard, it tries to write to the store with `+[MagicalRecord saveWithBlock:]` and crashes.

```
#0  0x391040ec in objc_retain
#1  0x0017febc in +[MagicalRecord(ErrorHandling) defaultErrorHandler:]
#2  0x00180636 in +[MagicalRecord(ErrorHandling) handleErrors:]
#3  0x0018d76e in -[NSManagedObjectContext(MagicalRecord) MR_contextWillSave:]
#4  0x2ecf1120 in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
#5  0x2ec65316 in _CFXNotificationPost
#6  0x2f649dcc in -[NSNotificationCenter postNotificationName:object:userInfo:]
#7  0x2eaa7b72 in -[NSManagedObjectContext save:]
#8  0x0018e048 in __70-[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:]_block_invoke21
#9  0x2eb0b7bc in developerSubmittedBlockToNSManagedObjectContextPerform
#10 0x2eb0b902 in -[NSManagedObjectContext performBlockAndWait:]
#11 0x0018ded0 in -[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:]
#12 0x0017eeb6 in __51+[MagicalRecord(Actions) saveWithBlock:completion:]_block_invoke
#13 0x2eb0b860 in developerSubmittedBlockToNSManagedObjectContextPerform_privateasync
#14 0x395f1296 in _dispatch_queue_drain$VARIANT$mp
#15 0x395f109a in _dispatch_queue_invoke$VARIANT$mp
#16 0x395f1d14 in _dispatch_root_queue_drain
#17 0x395f1f8c in _dispatch_worker_thread2
#18 0x3972cdbe in _pthread_wqthread
```

**Comment by BhavyaWhiz** [comment]
Hey did you guys get any solution to this. I have a similar situation and struggling to get the solution. Please help if you get the solution to handle the crash.
